from __future__ import annotations

import asyncio
from pathlib import Path
from typing import Protocol, cast

import docker
from docker.errors import DockerException

from controller.agent_client import AgentClient, AgentClientError, AgentLocalStateResponse
from controller.config import ControllerSettings
from controller.models import DeploymentStatus, EventType
from controller.state_store import StateStore


class IngressUpdater(Protocol):
    async def sync_service(self, service_id: str, reason: str) -> None: ...


class _LocalStateReader(Protocol):
    async def get_local_state(self, agent_url: str) -> AgentLocalStateResponse: ...


class IngressManager(IngressUpdater):
    def __init__(
        self,
        settings: ControllerSettings,
        store: StateStore,
        agent_client: AgentClient,
    ) -> None:
        self._settings = settings
        self._store = store
        self._agent_client = cast(_LocalStateReader, agent_client)
        self._lock = asyncio.Lock()

    async def sync_service(self, service_id: str, reason: str) -> None:
        if not self._settings.ingress_enabled:
            return
        if service_id != self._settings.ingress_active_service_id:
            return

        async with self._lock:
            decision = await self._resolve_target(service_id)
            if not decision.should_update:
                return

            next_target = decision.target
            changed = await self._write_upstream_config(next_target)
            if not changed:
                return

            if self._settings.nginx_reload_enabled:
                try:
                    await asyncio.to_thread(self._reload_nginx)
                except Exception as exc:
                    await self._store.append_event(
                        EventType.ingress,
                        "Ingress reload failed",
                        {
                            "service_id": service_id,
                            "reason": reason,
                            "error": str(exc),
                        },
                    )
                    return

            await self._store.append_event(
                EventType.ingress,
                "Ingress target updated",
                {
                    "service_id": service_id,
                    "target": next_target or self._settings.ingress_unavailable_target,
                    "reason": reason,
                },
            )

    async def _resolve_target(self, service_id: str) -> _SyncDecision:
        observed = await self._store.get_service_observed(service_id)
        placement = await self._store.get_placement(service_id)

        if observed is None:
            return _SyncDecision(should_update=True, target=None)
        if observed.status != DeploymentStatus.running:
            return _SyncDecision(should_update=True, target=None)
        if placement is None:
            return _SyncDecision(should_update=True, target=None)

        nodes = await self._store.list_nodes()
        node = next((item for item in nodes if item.node_id == placement.node_id), None)
        if node is None:
            return _SyncDecision(should_update=True, target=None)

        for _ in range(3):
            try:
                local_state = await self._agent_client.get_local_state(node.agent_url)
            except AgentClientError:
                await asyncio.sleep(0.2)
                continue

            workload = local_state.workloads.get(service_id)
            if workload is None or workload.container_ip is None:
                await asyncio.sleep(0.2)
                continue

            return _SyncDecision(
                should_update=True,
                target=f"{workload.container_ip}:{workload.service.internal_port}",
            )

        # Keep current target when active placement exists but agent read is transiently unavailable.
        return _SyncDecision(should_update=False, target=None)

    async def _write_upstream_config(self, target: str | None) -> bool:
        content = self._render_upstream_file(target)
        return await asyncio.to_thread(self._write_upstream_config_sync, content)

    def _write_upstream_config_sync(self, content: str) -> bool:
        output = Path(self._settings.ingress_upstream_file_path)
        output.parent.mkdir(parents=True, exist_ok=True)

        previous = output.read_text(encoding="utf-8") if output.exists() else ""
        if previous == content:
            return False

        output.write_text(content, encoding="utf-8")
        return True

    def _render_upstream_file(self, target: str | None) -> str:
        lines = [
            "# Generated by controller ingress manager. Do not edit manually.",
            f"# Active service: {self._settings.ingress_active_service_id}",
        ]
        if target is not None:
            lines.append(f"server {target};")
        return "\n".join(lines) + "\n"

    def _reload_nginx(self) -> None:
        try:
            client = docker.from_env()
            containers = client.containers.list(
                filters={
                    "label": [
                        f"com.docker.compose.project={self._settings.nginx_reload_compose_project_name}",
                        f"com.docker.compose.service={self._settings.nginx_reload_service_name}",
                    ]
                }
            )
            if not containers:
                raise RuntimeError("Nginx container not found for reload")
            result = containers[0].exec_run("nginx -s reload")
            if result.exit_code != 0:
                output = result.output.decode("utf-8", errors="ignore")
                raise RuntimeError(f"nginx reload failed: {output}")
        except DockerException as exc:
            raise RuntimeError("Failed to reload nginx via Docker socket") from exc


class _SyncDecision:
    def __init__(self, should_update: bool, target: str | None) -> None:
        self.should_update = should_update
        self.target = target
